### ISSUE TITLE
itdbloader.py error

### ISSUE THREAD

**Issue by ronech** [arkarkark/itdb#1]
bender:itdb rone$ ./itdbloader.py 
DEBUG:root:Starting ./itdbloader.py @ 2015-04-16 19:01:05.499557
INFO:root:Sanitizing xml into: /var/folders/4s/80qpdfsn3h35_grdnqdz7cyw0000gn/T/tmpLzB5Ho
INFO:root:tr -cd '  
 -~' <'/Users/rone/Music/iTunes/iTunes Music Library.xml' >'/var/folders/4s/80qpdfsn3h35_grdnqdz7cyw0000gn/T/tmpLzB5Ho'
INFO:root:loading /var/folders/4s/80qpdfsn3h35_grdnqdz7cyw0000gn/T/tmpLzB5Ho
INFO:root:Connecting to db
INFO:root:Clearing database
DEBUG:root:We care about these columns: User_ID, Track_ID, Name, Artist, Album, Genre, Kind, Size, Total_Time, Disc_Number, Disc_Count, Track_Number, Track_Count, Year, DATE_MODIFIED, Date_Added, Skip_Date, Skip_Count, Bit_Rate, Sample_Rate, Play_Count, Play_Date_UTC, Rating, Artwork_Count, Season, Persistent_ID, Track_Type, File_Type, File_Creator, Location, File_Folder_Count, Library_Folder_Count
INFO:root:Loading tracks data
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
INFO:root:Building Playlists
..Max name is 20 : Purgatory / Paradise
INFO:root:dir is : '/Users/rone/html/itdb'
DEBUG:root:rm -rf /Users/rone/html/itdb/album
DEBUG:root:rm -rf /Users/rone/html/itdb/artist
DEBUG:root:rm -rf /Users/rone/html/itdb/playlist
DEBUG:root:rm -rf /Users/rone/html/itdb/genre
INFO:root:Writing Stats
INFO:root:Connecting to db
Traceback (most recent call last):
  File "./itdbloader.py", line 333, in <module>
    it.WriteStats()
  File "/Users/rone/itdb/itdb2html.py", line 376, in WriteStats
    ratingspercent.append("%d%%" % ((ratings[x] \* 100) / totals["track"]))
IndexError: list index out of range
INFO:root:Closing db
INFO:root:Closing db
INFO:root:Cleaning up: /var/folders/4s/80qpdfsn3h35_grdnqdz7cyw0000gn/T/tmpLzB5Ho

I'm not sure if it's crapping out due to "Purgatory / Paradise" (directory name is "/Users/rone/Music/iTunes/iTunes Media/Music/Throwing Muses/Purgatory _ Paradise") or something else. How can i help track this down?

**Comment by ronech** [comment]
I will note that 'tracks' is fully populated, including the tracks from P / P.

**Comment by arkarkark** [comment]
Thanks for finding this! I think it happens when you don't have a full range of ratings in your library (e.g. nothing is rated so the are no 3\* values to count).

I think I fixed it with fc00cfaa7e34f11d38a613f939d77e51708a54a9

reopen if that doesn't work for you. glad you're trying to use this library!

**Comment by ronech** [comment]
Sounds right, i think that i have a smattering of 5-star tracks and the rest are unrated.  Will try again, thanks!
